# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\user\Desktop\3D-Skeleton-Display-Interface\src\canvas3d.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_canvas_3d_view(object):
    def setupUi(self, canvas_3d_view):
        canvas_3d_view.setObjectName("canvas_3d_view")
        canvas_3d_view.resize(400, 300)

        self.retranslateUi(canvas_3d_view)
        QtCore.QMetaObject.connectSlotsByName(canvas_3d_view)

    def retranslateUi(self, canvas_3d_view):
        _translate = QtCore.QCoreApplication.translate
        canvas_3d_view.setWindowTitle(_translate("canvas_3d_view", "Form"))
